import { test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { MongoClient } from "mongodb";
import { MongoMemoryReplSet } from "mongodb-memory-server";
import { authenticateA2A } from "../merchant/a2a/auth";
import { getA2AMerchantDirectory, merchantAgentCardJSON } from "../merchant/a2a/cards";
import { handleMerchantA2A } from "../merchant/a2a/transport";
import { createMerchantRFQProcessor } from "../merchant/a2a/service";
import { seedDemoMerchants } from "../merchant/server/seed";
import { MerchantAdminStore } from "../merchant/server/admin-store";
import type { MerchantRFQEnvelope } from "../merchant/a2a/contracts";
import { merchantBuyerClient, sendMerchantRFQ, sendNegotiation, getNegotiationResult } from "./helpers/merchant-buyer";
import type { NegotiationRequest } from "../merchant/negotiation/contracts";

test("official Buyer SDK exchanges A2A over HTTP with a disposable local MongoDB replica set", {
  skip: process.env.MERCHANT_A2A_LOCAL_INTEGRATION !== "true", timeout: 600000,
}, async t => {
  // Always generated by this process. No shared URI, environment database name, or .env loader is used.
  const replica = await MongoMemoryReplSet.create({ replSet: { count: 1, storageEngine: "wiredTiger", ip: "127.0.0.1" } });
  const client = new MongoClient(replica.getUri());
  const db = client.db("merchant_phase3_disposable");
  let origin = "";
  const token = "local-test-token-with-at-least-32-characters";
  const buyerId = "isolated-buyer-test";
  const env = () => ({ NODE_ENV: "test", MERCHANT_A2A_AUTH_MODE: "demo", MERCHANT_A2A_ORIGIN: origin,
    MERCHANT_A2A_DEMO_ENABLED: "true", MERCHANT_A2A_DEMO_TOKEN: token, MERCHANT_A2A_DEMO_BUYER_ID: buyerId });
  const processor = createMerchantRFQProcessor(async () => ({ client, db }));
  const server = createServer(async (incoming, outgoing) => {
    try {
      const path = new URL(incoming.url ?? "/", origin).pathname;
      let response: Response;
      if (path === "/api/a2a/discovery") response = Response.json(getA2AMerchantDirectory(origin));
      else {
        const route = /^\/api\/a2a\/([^/]+)(\/\.well-known\/agent-card\.json)?$/.exec(path);
        if (!route) response = new Response("Олдсонгүй.", { status: 404 });
        else if (route[2]) response = Response.json(merchantAgentCardJSON(route[1], origin));
        else {
          const chunks: Buffer[] = [];
          for await (const chunk of incoming) chunks.push(Buffer.from(chunk));
          const headers = new Headers();
          for (const [key, value] of Object.entries(incoming.headers)) if (value) headers.set(key, Array.isArray(value) ? value.join(",") : value);
          const request = new Request(`${origin}${path}`, { method: incoming.method, headers, body: Buffer.concat(chunks) });
          response = await handleMerchantA2A(request, route[1], { origin, processRFQ: processor,
            authenticate: (request, id) => authenticateA2A(request, id, env()) });
        }
      }
      outgoing.writeHead(response.status, Object.fromEntries(response.headers));
      outgoing.end(Buffer.from(await response.arrayBuffer()));
    } catch { outgoing.writeHead(500); outgoing.end("Туршилтын серверийн алдаа."); }
  });
  try {
    await client.connect();
    await seedDemoMerchants(client, db);
    // Fixtures use a fixed historical date; move only these disposable slots into the test's future.
    for (const slot of await db.collection("merchant_slots").find({}).toArray()) {
      const start = Date.now() + 86400000 * (1 + Number(String(slot.id).slice(-1)));
      await db.collection("merchant_slots").updateOne({ _id: slot._id }, { $set: { startsAt: new Date(start).toISOString(), endsAt: new Date(start + 8 * 3600000).toISOString() } });
    }
    await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
    const address = server.address();
    assert.ok(address && typeof address !== "string");
    origin = `http://127.0.0.1:${address.port}`;
    const directory = await (await fetch(`${origin}/api/a2a/discovery`)).json() as ReturnType<typeof getA2AMerchantDirectory>;
    const agents = new Map<string, Awaited<ReturnType<typeof merchantBuyerClient>>>(await Promise.all(directory.merchants.map(async merchant =>
      [merchant.merchantId, await merchantBuyerClient(merchant.agentCardUrl, token)] as const)));
    function envelope(merchantId: string, id: string, kind: "parts" | "repair" = "parts"): MerchantRFQEnvelope {
      return { contractVersion: "1", correlationId: `corr-${id}`, expiresAt: new Date(Date.now() + 3600000).toISOString(),
        rfq: { contractVersion: "1", id, merchantId, buyerId, createdAt: new Date(Date.now() - 1000).toISOString(), kind,
          vehicle: { make: "Toyota", model: "Prius 30", year: 2012 },
          items: [{ description: kind === "parts" ? "Урд гупер" : "Гупер солих", quantity: 1 }], status: "received" } };
    }
    const send = (e: MerchantRFQEnvelope) => sendMerchantRFQ(agents.get(e.rfq.merchantId)!, e);
    await t.test("discover five public cards and merchant-specific stored quotes", async () => {
      assert.equal(directory.merchants.length, 5);
      assert.equal(new Set(directory.merchants.map(m => m.a2aUrl)).size, 5);
      const expected = [65000000, 55000000, 110000000, 15000000, 12000000];
      for (const [index, merchant] of directory.merchants.entries()) {
        const card = await (await fetch(merchant.agentCardUrl)).text();
        assert.ok(!/minimumPrice|maxDiscount|stock|password/.test(card));
        const response = await send(envelope(merchant.merchantId, `valid-${index}`, merchant.kind));
        assert.equal(response.outcome, "quoted");
        assert.equal(response.quote!.total.amountMinor, expected[index]);
        assert.equal(response.quote!.reservation, false);
        assert.equal(response.quote!.merchantId, merchant.merchantId);
        assert.match(response.message, /[\u0400-\u04ff]/u);
        assert.ok(!/minimumPrice|maxDiscountBps|minimum.*acceptable/.test(JSON.stringify(response)));
      }
    });
    await t.test("Buyer SDK receives structured negotiation outcomes and retrieves durable results over A2A", async () => {
      const merchantId = "demo-prius-parts", agent = agents.get(merchantId)!;
      await db.collection("merchant_settings").updateOne({ merchantId, id: merchantId },
        { $set: { humanApprovalRequired: false, automaticNegotiationEnabled: true } });
      const input = envelope(merchantId, "a2a-negotiation");
      const original = await send(input);
      assert.ok(original.quote);
      const negotiation: NegotiationRequest = { contractVersion: "1", action: "negotiate_quote", rfqId: input.rfq.id,
        correlationId: input.correlationId, expiresAt: new Date(Date.now() + 600000).toISOString(),
        negotiation: { contractVersion: "1", id: "a2a-negotiation-1", merchantId, buyerId,
          createdAt: new Date(Date.now() - 1000).toISOString(), quoteId: original.quote.id, quoteRevision: original.quote.revision,
          requestedTotal: { amountMinor: 64000000, currency: "MNT" }, status: "requested" } };
      const result = await sendNegotiation(agent, negotiation);
      assert.equal(result.outcome, "accepted");
      assert.equal(result.quote?.revision, original.quote.revision + 1);
      assert.equal(result.quote?.reservation, false);
      assert.deepEqual(await getNegotiationResult(agent, input.rfq.id, negotiation.negotiation.id), result);
      assert.ok(!/minimumPrice|maxDiscountBps/.test(JSON.stringify(result)));
    });
    await t.test("auth, invalid schemas and payload scopes reject before private reads", async () => {
      const endpoint = `${origin}/api/a2a/demo-prius-parts`;
      assert.equal((await fetch(endpoint, { method: "POST", body: "{}" })).status, 401);
      const invalid = envelope("demo-prius-parts", "invalid");
      invalid.rfq.items[0].quantity = 0;
      await assert.rejects(send(invalid));
      const foreign = envelope("demo-japan-used", "foreign");
      await assert.rejects(sendMerchantRFQ(agents.get("demo-prius-parts")!, foreign));
      const buyer = envelope("demo-prius-parts", "foreign-buyer"); buyer.rfq.buyerId = "someone-else";
      await assert.rejects(send(buyer));
      assert.equal(await db.collection("merchant_rfqs").countDocuments({ id: { $in: ["invalid", "foreign", "foreign-buyer"] } }), 0);
    });
    await t.test("stock, vehicle, services and expiration outcomes persist", async () => {
      const stock = envelope("demo-japan-used", "stock"); stock.rfq.items[0].quantity = 20;
      const partial = await send(stock); assert.equal(partial.outcome, "partial"); assert.equal(partial.quote!.lines[0].quantity, 2);
      const unavailable = envelope("demo-prius-parts", "unavailable"); unavailable.rfq.items[0].description = "Тоормосны диск";
      assert.equal((await send(unavailable)).outcome, "declined");
      const vehicle = envelope("demo-prius-parts", "unsupported"); vehicle.rfq.vehicle.model = "Camry";
      assert.equal((await send(vehicle)).issues[0].code, "unsupported_vehicle");
      const expired = envelope("demo-prius-parts", "expired");
      expired.rfq.createdAt = new Date(Date.now() - 20000).toISOString(); expired.expiresAt = new Date(Date.now() - 10000).toISOString();
      assert.equal((await send(expired)).outcome, "expired");
      await db.collection("merchant_slots").updateMany({ merchantId: "demo-auto-care" }, { $set: { status: "blocked" } });
      assert.equal((await send(envelope("demo-auto-care", "no-slot", "repair"))).issues[0].code, "no_repair_slot");
      await db.collection("merchant_profiles").updateOne({ merchantId: "demo-quick-garage" }, { $set: { active: false } });
      assert.equal((await send(envelope("demo-quick-garage", "rejected", "repair"))).issues[0].code, "merchant_rejected");
    });
    await t.test("concurrent duplicates replay one committed RFQ, quote version and audits", async () => {
      const request = envelope("demo-prius-parts", "duplicate");
      const results = await Promise.all(Array.from({ length: 5 }, () => send(request)));
      results.forEach(r => assert.deepEqual(r, results[0]));
      assert.equal(results[0].outcome, "quoted");
      assert.equal(await db.collection("merchant_rfqs").countDocuments({ merchantId: request.rfq.merchantId, id: request.rfq.id }), 1);
      assert.equal(await db.collection("merchant_quotes").countDocuments({ merchantId: request.rfq.merchantId, rfqId: request.rfq.id }), 1);
      assert.equal(await db.collection("merchant_audit_events").countDocuments({ correlationId: request.correlationId }), 3);
      assert.equal(await db.collection("merchant_rfq_processing").countDocuments({ id: request.rfq.id, status: "quoted" }), 1);
      const conflicting = structuredClone(request); conflicting.rfq.items[0].quantity = 2;
      await assert.rejects(send(conflicting));
      assert.equal((await send(request)).quote!.revision, 1);
    });
    await t.test("persistent dashboard updates change new quotes without reservation or cross-merchant edits", async () => {
      const admin = new MerchantAdminStore(client, db, "demo-prius-parts");
      const item = (await admin.list("inventory")).find(item => item.record.id.endsWith("bumper"))!;
      await admin.save("inventory", { ...item.record, price: { amountMinor: 70000000, currency: "MNT" }, stock: 3 }, item.version);
      const result = await send(envelope("demo-prius-parts", "price-edit")); assert.equal(result.quote!.total.amountMinor, 70000000);
      await assert.rejects(new MerchantAdminStore(client, db, "demo-japan-used").save("inventory", item.record, item.version));
      assert.equal((await db.collection("merchant_inventory").findOne({ merchantId: "demo-prius-parts", id: item.record.id }))!.stock, 3);
      const restartRequest = envelope("demo-prius-parts", "restart");
      const persisted = await send(restartRequest);
      const reconnected = new MongoClient(replica.getUri());
      try {
        await reconnected.connect();
        assert.deepEqual(await createMerchantRFQProcessor(async () => ({ client: reconnected, db: reconnected.db(db.databaseName) }))(
          "demo-prius-parts", buyerId, restartRequest), persisted);
      } finally { await reconnected.close(); }
    });
    await t.test("malformed private data persists a safe failed result and audit without a quote", async () => {
      await db.collection("merchant_inventory").updateOne({ merchantId: "demo-oem-center", id: "demo-oem-center-bumper" }, { $set: { stock: -1 } });
      const request = envelope("demo-oem-center", "processing-failure");
      const result = await send(request);
      assert.equal(result.outcome, "failed");
      assert.ok(!JSON.stringify(result).includes("minimumPrice"));
      assert.equal(await db.collection("merchant_quotes").countDocuments({ merchantId: request.rfq.merchantId, rfqId: request.rfq.id }), 0);
      assert.equal(await db.collection("merchant_rfq_processing").countDocuments({ merchantId: request.rfq.merchantId, id: request.rfq.id, status: "failed" }), 1);
      assert.equal(await db.collection("merchant_audit_events").countDocuments({ merchantId: request.rfq.merchantId, entityId: request.rfq.id, action: "rfq_failed", outcome: "failure" }), 1);
      assert.deepEqual(await send(request), result);
    });
  } finally {
    await new Promise<void>(resolve => { server.close(() => resolve()); server.closeAllConnections(); });
    await client.close();
    await replica.stop();
  }
});
